#+title:        How I learn English
#+date:         2023-04-25
#+DRAFT:        false
#+filetags:     :english:learning:
#+TAGS[]:       English, Learning
#+CATEGORIES[]: Review
#+identifier:   20230425T165757

如何不靠词汇量学习英语，这是我一年左右学习英语的经验&总结。

# more

* 序0：一年多自学的总结
书籍顺序：《旋元佑文法》&《旋元佑文法解题》、《SICP》、《Calculus with Analytic Geometry》（后文数学指代这本书）
一年前状态：英语很差，看文档基本靠翻译软件，无法自行阅读，并且比较抗拒阅读英文内容。

目前状态：
- 能够自行阅读数学的内容，自我能理解绝大部分，哪怕是遇到很多不熟悉的专业术语，也能通过分析语法结构来尝试猜测内容大概的含意。阅读其他的英语内容也不再感觉抗拒。
- 词汇量偏科严重（计算机、数学术语很熟悉，但是日常用语不熟悉），能输出一些简单的句子，但是复杂的语法已经忘得差不多了
- 口语发音还是不标准，但是听力有提升，能够通过单词来推它的大概发音

* 重拾英语

学习英语的目的：让我能看懂英文内容，包括但不限于：技术文档、书籍、英语社区论坛（reddit、github）等。

** 尝试了的方法

其实几年前就有所行动，但是每次都无法坚持下来，不是倒在背单词、记音标的路上，就是无法坚持阅读英语小说或看美剧。

总结下失败的原因：
- 基础太差：完全没有英语语法的基础，高考和大学完全是靠的死记硬背
- 无法坚持：我个人很讨厌死记硬背，这应该是坚持不下来的部分原因，还有就是感觉不到进展，自然也就失去动力了。
- 兴趣：上述方式都是只为了学习英语而做的，所有的目的也只是为了学习英语。但我本身对英语不感兴趣。

** 为什么这次成功了

- 对症下药：优先学习了英语语法，两本旋元佑的书籍是非常不错的文法学习书籍，是作者站在学生的视角出的书，很多内容都在强调 =理解= 而非 =记忆= 。
  前半部分补足英语语法基础，后半部分讲解语法的高阶用法。适合多次观看、回顾。
- 坚持&兴趣：为了坚持下去，我随后阅读了《SICP》、《Calculus with Analytic Geometry》 选这两本书的原因是和我想要发展的方向契合。
  - 第一本书啃的很是费劲，但也不是毫无所获，英语语法和词汇量有所提升，也学习了一些编程知识
  - 第二本书：刚开始很费劲，要熟悉新作者的语法习惯、惯用词以及相应的数学术语。好在这是本超赞的书，越看越上头。这个可以说是我坚持英语下来的原因。
    到后面我几乎整天都在看这本书、做习题。大概持续了小半年，当我看的差不多，为后续计划做准备时才发现阅读其他的英文材料已经相当轻松了（比较之前的状态）。


* 详细学习路径&建议

=此是我个人的学习路径、建议，请谨慎思考后选择性的采纳。=

1. [[https://www.coursera.org/learn/learning-how-to-learn][Learning How to Learn]]， 强烈推荐学习这门课程，这门课程所教授的知识在我这一年多的自学经历中相当受用。
   包括但不限于以下部分：
   - 记忆：课程并不推崇刻意的去锻炼记忆，而是通过将所学的知识点建立联系，形成区块，降低大脑负担。
   - 专注&发散模式的概念以及如何合理的利用各自的长处
   - 锻炼对于学习的帮助
2. [[https://book.douban.com/subject/34840714/][《旋元佑文法》]]&《旋元佑文法解题》这是两个配套书籍，是旋元佑系列丛书中的两本。
   阅读建议：对于像我这样的英语零基础或者基础很差的人来说，我的建议是第一次阅读时能理解的尽量理解书中的概念，对应的单词短语的用法如果记不住可以暂时忽略。
   每读完一章，做对应的习题。可以不求甚解，但需要记录下问题，留待之后阅读回顾。
   - 由于是台湾作者，因此用语习惯也是遵从台湾的翻译，我推荐按照书中翻译来更便于理解，例如：宾语被译为受语，是动作（动词）的接受对象。
   - 书中并没有我在初高中学习语法时的表、状、补等术语，这类使人 =迷糊= 的概念都被作者梳理成便于读者理解的概念。
   - 在阅读文法大半内容后可以多多尝试阅读英语文本，进行实战练习。
3. [[https://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs?useskin=vector][《SICP》]] 这本书是当时我一边看文法一边看的第一本英语书，略感吃力，但是当发现《文法》书中的知识点能为我所用，且慢慢我能看懂的句子越来越长，越来越复杂，给我很大的信心支持。
   但是我当时阅读的时候还是缺少了读书的经验，不知道如何处理各种知识点，如何建立关联关系，如何消化知识点。
   书是好书，只是我当时太笨。
4. [[https://www.goodreads.com/book/show/241480.Calculus_With_Analytic_Geometry][《Calculus with Analytic Geometry》]] 这本书讲的是数学，但又不仅仅是数学，涉及到经济学、物理学、电磁场等等。
   书中的知识点越学越有意思，把我以前对数学的刻板印象完全改观。
   不过更重要的是书中如何拆分知识点，由于越到后面越需要你对全书的知识点都融汇贯通，你越能体会作者在章节安排、习题布置上的精妙，也越能找到适合你的学习方法。


* 一些对英语学习的建议

- 初期的准备工作：先审查一下自身
  1. 搞明白你学习英语的目的
  2. 你现在最需要的东西：词汇量？口语？还是阅读能力？
  3. 搜索大量的书籍，通过别人的评价来简要了解这本书值不值得你花时间去阅读，不要等看了一半的书才觉得这本书很烂、或者不适合你。
- 往兴趣靠拢：网上有大量的推荐美剧学习、小说学习，不要被他们迷了眼，适合他们的不一定适合你，找到适合的你才能长期坚持下去。
  我的方式：定下未来的发展方向，然后找对应方向的书籍学习。
- 词汇
  1. 字典：欧陆词典+英英翻译的词典，英语翻译的好处是完全用英语解释（初学者可能有点难受），且阅读的时候也会接触其他相关的单词。
  2. 不去主动记忆词汇，当你有一些语法基础后，你能知道哪些句中的成分可以暂时跳过。只记忆一些频率较高的词汇。
  3. [[vocabulary.com][Vocabulary.com]] 也是个不错的网站，最近才发现。通过多种方式来学习词汇，适合在有一些语法基础后学习。

或许有人会问如何提升词汇量？
回答这个问题前，我先反问你，你需要的是真的是 ~提升词汇量~ 吗？
我也曾陷入一样的误区，以为必须要把英语文本中的单词完完全全的记住才能读懂文章。实际恰恰相反，我曾遇到单词都认识但仍旧读不懂句子的情况。

正如我的需求： =能理解英文文本的含意=
所以你真实的需求是提升词汇量吗？如果你是学生，这或许是“对”的，但是对于大部分想要重拾英语的人，提升词汇量并不能 =显著= 的带来阅读理解力上的提升。

真正的能带给你理解力提升的是文法。
当一个单词重复多次你还是无法记忆的时候，你就可以主动去记忆它，甚至于当它的含意很多时，你也只需要记忆部分，剩下的完全可以等你真正需要的时候再去记忆。


人脑像是 ~CPU~ ，它应该做的事是去 =理解事物、思考如何运用= ，而不是 _机械、死板_ 的像一个 ~硬盘~ 一样去存储他们。

=解放大脑，才能解放思维。=

** 为什么要推荐阅读英文书籍

举个例子：你的目的是赏月，当你可以直接抬头看月亮的时候，你不会想着低头看池塘中的月色，池塘中的虽然也有它的“独特美”，但不是 =真正= 的月亮。
我觉得什么译本都无法表达作者真实的想法。（PS：特别是我在看SICP时，我一边看的英文书籍，偶尔用买的中文纸质做对照，有一个图中的“平衡”把我整笑了，那个小结的含意都应该是“余额”）

阅读英语时，你本身大脑也完全代入，每一个单词（至少是你认得的）都会从大脑中经过，你大脑会尝试去排列、组合或者省略部分不认识且不太重要的单词，或者尝试用上下文解释
某个术语，也就每时每刻都在实战中。只要你能坚持下去，你的提升会是相当迅速的。

** 一个例子解释语法的作用

Mary is a beautiful woman.

对于没有语法基础的人，读这个句子像是在做填空题 ~A B C D E~ 。必须要记得对应单词的含意才能把“读懂”句子。
如果你不记得其中 =某个= 单词的含意，那就大概率无法读懂句子。

当你认得语法，你可以把句子的成分识别出来，句子可以被简化为 ~Mary is woman~ 。我们就只需要记得这三个单词的含意。
甚至由于大部分的句子很容易被简化为 ~主语 动词 受语~ 的结构。
主语、受语都是某个名词，而动词也非常好辨别。那么我们主要需要记忆的词汇量就仅仅是名词+动词，便能大概读懂句子的含意。
然后再结合书中上下文以及最终通过翻译软件来辅助理解。

语法可以大大减少你对词汇量的需求，并且这只是它的一个好处。

* 相关资源
- [[https://www.bilibili.com/video/BV1ns4y1A7fj][罗肖尼：如何永远学会一个单词？]] 看完文章还觉得迷惑？强烈推荐这个视频，以及这个UP其他关于英语学习的视频。
- [[https://my.vocabularysize.com][词汇量自测]]
  - [[https://my.vocabularysize.com/result/71ffbe2554f0ae3f28f737303da7772f][我的词汇量：5200，截止2023-04-27]]
- [[https://forum.freemdict.com/][FreeMdict]] 大量的学习资料：字典、书籍等。
